import = ["/home/manahan/.config/alacritty/nord.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "SauceCodePro NF"
style = "Regular"


[window.dimensions]
columns = 100
lines = 40
